name: buscador
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.5
  intl: ^0.18.0
  dio: ^5.1.0
  cupertino_icons: ^1.0.2
  csv: ^5.0.1
  path_provider: ^2.0.14
  share_plus: ^6.3.2
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:

  uses-material-design: true

  fonts:
    - family: rawline
      fonts:
        - asset: assets\fonts\rawline-500.ttf
